Repository Automattic/newspack-content-converter, pull requests merged in 2020-01, with the labels that each got.

#35 WP-Prettier coding standards applied
  assets/src/content-converter/index.js
  assets/src/content-repatcher/index.js
  assets/src/conversion/index.js
  assets/src/index.js
  assets/src/patchers/index.js
  assets/src/settings/index.js
  assets/src/style.css
  assets/src/utilities/index.js
  dependency-includer-script.php
  lib/class-conversionprocessor.php
  lib/class-converter.php
  lib/class-convertercontroller.php
  lib/class-installer.php
  lib/content-patcher/patchers/class-imgpatcher.php
Labels: [Status] Approved, enhancement

#36 Add/retry failed conversions
  assets/src/content-converter/index.js
  assets/src/content-repatcher/index.js
  assets/src/conversion/index.js
  assets/src/index.js
  assets/src/patchers/index.js
  assets/src/utilities/index.js
  lib/class-config.php
  lib/class-conversionprocessor.php
  lib/class-convertercontroller.php
  lib/class-installer.php
  newspack-content-converter.php
  package-lock.json
  package.json
Labels: enhancement

#37 Skip converting invalid content
  assets/src/index.js
  lib/class-convertercontroller.php
  lib/class-installer.php
  newspack-content-converter.php
Labels: [Status] Approved, enhancement

#39 Node 12.x Support, Updated NPM Scripts
  README.md
  package-lock.json
  package.json
Labels: Infrastructure, [Status] Needs Review

#41 Add Newspack Components UI to the plugin
  assets/src/conversion/index.js
  assets/src/index.js
  assets/src/settings/index.js
  assets/src/style.css
  assets/src/style.scss
  lib/class-converter.php
  lib/class-convertercontroller.php
  package-lock.json
  package.json
Labels: [Status] Needs Review

#43 Reorder admin pages to display "Run conversion" first
  assets/src/content-converter/index.js
  assets/src/conversion/index.js
  assets/src/settings/index.js
  lib/class-converter.php
Labels: [Status] Needs Review

#45 Content Converter: Update interface based on Newspack Components
  assets/src/content-converter/index.js
  assets/src/style.scss
Labels: [Status] Needs Review

#44 Safer post types detection and setting
  lib/class-installer.php
Labels: [Status] Approved, bug
